apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.1-1.0.0
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  storage:
    size: 4Gi
    storageClass: local-data
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-immich
spec:
  name: immich
  owner: app
  cluster:
    name: cluster-immich
  extensions:
    - name: vchord 
      ensure: present    
    - name: earthdistance
      ensure: present    