apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.0-0.5.3
  postgresql:
    shared_preload_libraries:
      - vchord.so
  storage:
    size: 4Gi
    storageClass: local-data
  bootstrap:
    postInitApplicationSQL:
      - CREATE EXTENSION IF NOT EXISTS "vector";
      - CREATE EXTENSION IF NOT EXISTS "vectors";
      - CREATE EXTENSION IF NOT EXISTS "cube";
      - CREATE EXTENSION IF NOT EXISTS "earthdistance";
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-immich
spec:
  name: immich
  owner: app
  cluster:
    name: cluster-immich
  extensions:
    - name: vchord
      ensure: present    
    - name: earthdistance
      ensure: present    