apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: immich
spec:
  entryPoints:
    - https
  routes:
    - match: HostSNI(`immich.buergerhoff.com`)
      services:
        - name: immich-server
          port: 2283