apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.3.0
    helm:
      valuesObject:
        ports:
          traefik:
            # TODO: We might want to disable this in the future for security reasons
            expose:
              default: true
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.buergerhoff.com`)
        additionalArguments:
          - "--api.insecure=true"
        certificatesResolvers:
          main:
            acme:
              email: veith.buergerhoff@gmail.com
              storage: "/data/acme.json"
              tlschallenge: {}
        service:
          annotations:
            metallb.io/loadBalancerIPs: "192.168.12.230,2a04:4540:6500:99::230"
          ipFamilyPolicy: RequireDualStack
          ipFamilies:
            - IPv4
            - IPv6
        # extraObjects:
        #   - apiVersion: traefik.io/v1alpha1
        #     kind: IngressRoute
        #     metadata:
        #       name: traefik-dashboard
        #     spec:
        #       routes:
        #         - match: Host(`traefik.buergerhoff.local`)
        #           kind: Rule
        #           services:
        #             - name: api@internal
        #               kind: TraefikService
    providers:
      kubernetesCRD:
        allowCrossNamespace: true

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
