apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
stringData:
  config.yaml: |
    clusters:
      - url: https://buergerhoff.local:8006/api2/json
        insecure: false
        token_id: "kubernetes-csi@pve!csi"
        token_secret: "da76b4a5-a265-48b1-a370-ca55e9005532"
        region: Home