apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  buergerhoff.server: |
    buergerhoff buergerhoff.lan {
      hosts {
        192.168.12.220 pve.buergerhoff.lan buergerhoff.lan buergerhoff
        fallthrough
      }
    }
