apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
spec:
  addresses:
  - 192.168.12.230-192.168.12.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first
specs:
  ipAddressPools: 
    - first-pool