apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/VerticalVeith/homelab
    targetRevision: HEAD
    path: manifests/base/cloudnativepg/install
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
