apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorio
  namespace: argocd
spec:
  destination:
    namespace: factorio
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: factorio-server-charts
    repoURL: https://sqljames.github.io/factorio-server-charts
    targetRevision: 2.5.2
    helm:
      valuesObject:
        persistence:
          storageClassName: local-data
          enabled: true
          accessMode: ReadWriteOnce

        factorioServer:
          enable_space_age: true
          require_user_verification: true

        service: 
          type: ClusterIP
          ipFamilyPolicy : RequireDualStack
          ipFamilies:
            - IPv4
            - IPv6
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: factorio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
