apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: factorio-router
  namespace: factorio
spec:
  entryPoints:
    - factorio
  routes:
    - services:
        - name: factorio-factorio-server-charts
          port: 34197
          nativeLB: true
