apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/VerticalVeith/homelab
    targetRevision: HEAD
    path: manifests/base/metallb/install
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/sync-options: Prune=false, Delete=false
