apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argo-cd.yaml
  - base/argocd-image-updater.yaml
  - base/cluster-config.yaml
  - base/metallb.yaml
  - base/sync-argoproj.yaml
