apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/metallb/metallb//config/native?ref=main&timeout=90s
  - base/pools.yaml
  - base/advertisements.yaml

patches:
  - path: overlays/patch-priority-class.yaml
    target:
      kind: Deployment
  - path: overlays/patch-priority-class.yaml
    target:
      kind: StatefulSet
  - patch: |
      op: add
      path: /spec/template/spec/0/nodeSelector/\"node-role.kubernetes.io/control-plane\"
      value: "true"
    target:
      kind: Deployment