apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-data
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/data
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete