apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
stringData:
  config.yaml: |
    clusters:
      - url: https://buergerhoff.local:8006/api2/json
        insecure: false
        token_id_file: "/etc/proxmox/token_id"
        token_secret_file: "/etc/proxmox/token_secret"
        region: Home