apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-lvm
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: local
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
