apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
stringData:
  config.yaml: |
    clusters:
      - url: https://pve.buergerhoff.lan:8006/api2/json
        insecure: false
        token_id: "kubernetes-csi@pve!csi"
        token_secret: "ff39049b-85b7-4028-821a-f9c763bb202c"
        region: home
