apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-aged
  namespace: argocd
spec:
  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    chart: minecraft
    targetRevision: 5.0.0
    helm:
      valuesObject:
        resources:
          requests:
            memory: 2048Mi
        minecraftServer:
          eula: true
          memory: 4G
          type: MODRINTH
        extraEnv:
          - name: MODRINTH_MODPACK
            value: aged
        persistence:
          dataDir:
            enabled: true
          storageClass: local-data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
