apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-homies
  namespace: argocd
spec:
  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    chart: minecraft
    targetRevision: 5.0.0
    helm:
      valuesObject:
        resources:
          requests:
            memory: 2048Mi
        minecraftServer:
          eula: true
          memory: 4G
          difficulty: hard
          extraServiceSpec:
            ipFamilyPolicy: DualStack
            ipFamilies:
              - IPv4
              - IPv6
        persistence:
          dataDir:
            enabled: true
          storageClass: local-data
        extraDeploy:
          - apiVersion: traefik.io/v1alpha1
            kind: IngressRouteTCP
            metadata:
              name: minecraft-homies
            spec:
              entryPoints:
                - minecraft
              routes:
                - match: HostSNI(`*`)
                  services:
                    - name: minecraft-homies
                      port: 25565
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
