apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-router
  namespace: argocd
spec:
  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    chart: mc-router
    targetRevision: 5.0.0
    helm:
      valuesObject:
        minecraft:
          type: ClusterIP
        extraDeploy:
          - apiVersion: traefik.io/v1alpha1
            kind: IngressRouteTCP
            metadata:
              name: '{{ template "mc-router.fullname" . }}'
            spec:
              entryPoints:
                - minecraft
              routes:
                - match: HostSNI(`*`)
                  services:
                    - name: '{{ template "mc-router.fullname" . }}'
                      port: 25565
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
