apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stoneblocks-pvc
  namespace: minecraft
spec:
  storageClassName: proxmox-lvm
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
