apiVersion: v1
kind: PersistentVolume
metadata:
  name: stoneblocks-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: proxmox-data-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stoneblocks-pvc
  namespace: minecraft
spec:
  storageClassName: proxmox-data-xfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi