apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-stoneblock
  namespace: minecraft
spec:
  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    chart: minecraft
    targetRevision: 5.0.0
    helm:
      valuesObject:
        minecraftServer.eula: true
        persistence:
          storageClass: proxmox-lvm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
