apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-village
  namespace: argocd
spec:
  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    chart: minecraft
    targetRevision: 5.0.0
    helm:
      valuesObject:
        resources:
          requests:
            memory: 2048Mi
        serviceAnnotations:
          "mc-router.itzg.me/externalServerName": "village.buergerhoff.com,village.buergerhoff.lan"
        minecraftServer:
          eula: true
          memory: 4G
          difficulty: hard
          type: AUTO_CURSEFORGE
          autoCurseForge:
            apiKey:
              existingSecret: "curseforge"
              secretKey: cf-api-key
            pageUrl: "https://www.curseforge.com/minecraft/modpacks/life-in-the-village-4"
            fileId: "7279460"
        extraServiceSpec:
          ipFamilyPolicy: RequireDualStack
        persistence:
          dataDir:
            enabled: true
          storageClass: local-data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
