apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
spec:
  destination:
    namespace: paperless
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: oci://ghcr.io/gabe565/charts/paperless-ngx
    chart: paperless-ngx
    targetRevision: 0.24.1
    helm:
      valuesObject:
        # see https://github.com/gabe565/charts/issues/783
        global:
          security:
            allowInsecureImages: true
        redis:
          image:
            repository: bitnamilegacy/redis
        env:
          TZ: "Europe/Berlin"
          PAPERLESS_URL: https://dms.buergerhoff.com
          PAPERLESS_ALLOWED_HOSTS: dms.buergerhoff.com
          PAPERLESS_CSRF_TRUSTED_ORIGINS: https://dms.buergerhoff.com

        persistence:
          data:
            enabled: true
            storageClass: local-data
            accessMode: ReadWriteOnce
            size: 1Gi
          media:
            enabled: true
            storageClass: local-data
            accessMode: ReadWriteOnce
            size: 8Gi
          export:
            enabled: true
            storageClass: local-data
            accessMode: ReadWriteOnce
            size: 1Gi
          consume:
            enabled: true
            storageClass: local-data
            accessMode: ReadWriteOnce
            size: 4Gi
        ingress:
          main:
            enabled: true
            className: traefik
            annotations:
              kubernetes.io/ingress.class: traefik
              kubernetes.io/tls-acme: "true"
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.tls.certresolver: main
            hosts:
              - host: dms.buergerhoff.com
                paths:
                  - path: /
                    pathType: ImplementationSpecific
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
