# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: homelab-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   type: git
#   url: https://github.com/VerticalVeith/homelab
#   project: sync
