apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: home-assistant
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    targetRevision: 0.3.38
    helm:
      valuesObject:
        additionalVolumes:
          - hostPath:
              path: >-
                /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_ec0cf9e65a53ef119fef24e0174bec31-if00-port0
              type: CharDevice
            name: zigbee

        additionalMounts:
          - mountPath: /dev/ttyUSB0
            name: zigbee

        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClass: local-data

        securityContext:
          # Required for accessing USB devices
          privileged: true

        ingress:
          enabled: true
          className: traefik
          annotations:
            kubernetes.io/ingress.class: traefik
            kubernetes.io/tls-acme: "true"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: home.buergerhoff.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - certResolver: main

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
